version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=test
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
