name: sanitizer HW 3

on:
  push:
    branches:
      - hw*
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./${{env.BRANCH_NAME}}/Cargo.toml

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippyx`

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./${{env.BRANCH_NAME}}/Cargo.toml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./${{env.BRANCH_NAME}}/Cargo.toml